### ISSUE TITLE
[Dungeon] Den of the Vixen

### ISSUE THREAD

**Issue by sundayz** [Collines/Venoxis-BugTracker#1]
**To-do list for the Den of the Vixen**

_Creature Scripts_
- [x] Living Magma
- [x] Den Protector
- [x] Fiery Runt
- [x] Fire-bathed Construct
- [x] Conflagrant Guardian
- [x] Magma-spewing Totem
- [x] Sworn Cultist

_Boss Scripts_
- [x] Magravel, the Substratal
- [x] Gurak

_Progress_
- [x] Dev realm
- [x] Public dev realm
- [ ] Tested by QA team.
