### ISSUE TITLE
Transmogrification Vendor TO-DO

### ISSUE THREAD

**Issue by Insaniuz** [Collines/Venoxis-BugTracker#5]
- [x] Make the vendor as follows:
1.  Armor Sets
2. Weapons 

1.1 Arena Season Sets
1.2 Raid Tier Sets
1.3 Other sets (gathered by me using some ideas that I can gather from wowhead for ex.)
2.1 Arena Season Weapons
2.2 Raid Weapons
2.3 Other weapons (can be custom weapons with good looking display ids as well.)

1.1.1 - 1.1.10 Arena Season 1-8 (incl. Savage and Hateful Gladiator)
1.2.1 - 1.2.11 Raid Tier 1- 10.5

- [x] Remove stats from all the items I have gathered in the vendor

- [x] Remove the items from other npc_vendor entries and loot tables.

- [x] Add costs to the items. 
Armor sets will cost 1 MG per item
Weapons will cost 3 MG per item
