### ISSUE TITLE
Premium Item

### ISSUE THREAD

**Issue by Collines** [Collines/Venoxis-BugTracker#8]
# Premium Item
Since we won't provide pay to win content, we're creating an item that has no stats (**_non-equip-able_**) which allow you to train, reset talents, pocket bank, auctionhouse, summon group member, appear to group leader, check MG, morph, scale your size, repair your items and buff you.

**This item will be only for VIP members only.**

## Tasks:-
- [x] Train feature
- [x] Reset talent (_Wipe confirm through item_)
- [x] Pocket Bank feature
- [x] Auctionhouse (_Through item_)
- [x] Summon & Appear feature (_Works only for your group members with a loading bar to avoid abusing_)
- [x] Check Magic Gold (_MG_)
- [x] Dressing Service (_Morphing and scaling your size_)
- [x] Repair armor feature
- [x] Buff feature

**Comment by Collines** [comment]
http://prntscr.com/hleaw0
